"""Linking Book and Review tables

Revision ID: 1c8640f6bd3d
Revises: 30971bf2cda4
Create Date: 2018-05-17 23:14:57.456341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c8640f6bd3d'
down_revision = '30971bf2cda4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('pub_year', sa.String(length=64), nullable=True))
    op.drop_column('book', 'pub_yeark')
    op.add_column('review', sa.Column('book_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'review', 'book', ['book_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.drop_column('review', 'book_id')
    op.add_column('book', sa.Column('pub_yeark', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('book', 'pub_year')
    # ### end Alembic commands ###
